# Generated by Django 3.1.1 on 2020-10-05 06:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflearn_lecture', '0002_mytext_board_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytext',
            name='board_text',
        ),
        migrations.AddField(
            model_name='mytext',
            name='aa',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
