# Generated by Django 3.1.1 on 2020-10-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflearn_lecture', '0009_auto_20201006_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytext',
            name='lecture_video1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mytext',
            name='lecture_video2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mytext',
            name='lecture_video3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mytext',
            name='lecture_video4',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
